name: DAST Scan

on:
  push:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar escaneo ZAP completo
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          # URL a escanear (puede ser un servicio que hayas desplegado en el workflow)
          target: 'http://localhost:3030'
          # Nivel de riesgo mínimo (e.g. Low, Medium, High)
          risk: 'Medium'
          # Nivel de confianza mínimo (e.g. Low, Medium, High)
          confidence: 'Medium'

      - name: Guardar reporte
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: ./zap_report.html
