name: DAST Scan

on:
  push:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Escaneo OWASP ZAP Full
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3030'        
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: >
            -config scanner.attackStrengthDefault=LOW
            -config scanner.alertThresholdDefault=MEDIUM
          artifact_name: 'ZAP-Report'

      - name: Subir artefacto con el reporte
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report_html.html
