name: DAST Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci

      - name: Iniciar la aplicación
        run: npm run start &

      - name: Esperar a que la app esté lista
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://localhost:3000; then
              echo "App arriba 🎉"
              exit 0
            fi
            echo "Esperando… ($i/30)"
            sleep 2
