name: DAST Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      app:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias y arrancar la app
        run: |
          npm ci
          npm run start &

      - name: Esperar a que la aplicación esté lista
        run: sleep 30

      - name: Instalar OWASP ZAP
        run: sudo apt-get update && sudo apt-get install zaproxy -y

      - name: Ejecutar escaneo con OWASP ZAP
        run: zaproxy -cmd -autorun zap_scan.yaml

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
          path: zap_report.html
