name: ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    name: Ejecutar ZAP Scan completo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Iniciar contenedor de la aplicación
        run: |
          docker run -d --name myapp -p 3000:3000 mi-imagen:latest
      - name: Esperar a que la aplicación esté lista
        run: |
          npx wait-on http://localhost:3000

      - name: ZAP Spider
        uses: zaproxy/action-spider@v1
        with:
          target: http://localhost:3000
          max-duration: 2

      - name: ZAP Active Scan
        uses: zaproxy/action-active-scan@v1
        with:
          target: http://localhost:3000
          recurse: true
          max-duration: 5

      - name: Generar reporte HTML
        uses: zaproxy/action-report@v1
        with:
          format: traditional-html
          filename: zap_report.html
          title: "ZAP Scan Report"

